apiVersion: v1
kind: Service
metadata:
  labels:
    app: shopizer-es
  name: shopizer-es
  namespace: shop
spec:
  ports:
  - name: "9200"
    port: 9200
    targetPort: 9200
  selector:
    app: shopizer-es
