apiVersion: v1
kind: Service
metadata:
  labels:
    app: shopizer-db
  name: shopizer-db
  namespace: shop
spec:
  clusterIP: None
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    app: shopizer-db
